language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
services:
    - redis-server
install:
    - pip install -e .
    - pip install coveralls pytest-cov
script:
    - make unit
after_success:
    - coveralls
